### PR TITLE
[OPENENGSB-3339] replaced static repo path with fetching the path from t...

### PR DESCRIPTION
**Pull request by CHavlicek**
...he settings.xml via the M2_HOME enviroment variable

### CODE REVIEW

**Comment by anpieber** [comment]
any updates on this one?

**Comment by CHavlicek** [comment]
Ups, totally forgot about it. I will send you the changes this week

**Comment by anpieber** [comment]
Thank you very much

**Comment by CHavlicek** [comment]
updated for both ways of configuring the settings.xml

**Comment by anpieber** [comment]
I've merged this already from a different pull request

**Pull request closed without merging**
